### ISSUE TITLE
Task drag & Drap value erased

### ISSUE THREAD

**Issue by zerlite2112** [sonyxperiadev/BacklogTool#13]
Hi,
I added a new task, entered some information which I didn't save yet and I arrange the task drag and drop it, it updates the panel but the values of the new task is set to default, the one that I had previously typed is erased.

Thanks,
Gerald

**Comment by fredriklindman** [comment]
Hi!

Yes, that is a problem. A very quick "solution" would be to lock the user from drag and drop until he or she exits "edit mode" by saving or reverting again. What do you think about that?

Fredrik

**Comment by fredriklindman** [comment]
Issue solved in version 1.2.0, closing
