### ISSUE TITLE
Note fields

### ISSUE THREAD

**Issue by GLundh** [sonyxperiadev/BacklogTool#17]
There should be a way to add arbitrary foot notes to a story or task. For instance URLs pointing towards code patches or Issue IDs.

**Comment by frazor** [comment]
And automatic thumbnail of image-URLs perhaps?

**Comment by rsandell** [comment]
Notes should have a timestamp and info on what user wrote it.

Notes could also be used by the system itself as an eventlog. For example when status is changed and when a story is archived.

**Comment by fredriklindman** [comment]
Implemented in version 1.3.0, closing
