### ISSUE TITLE
Filter on ids

### ISSUE THREAD

**Issue by fredriklindman** [sonyxperiadev/BacklogTool#25]
Implement a filter which can sort out specific story ids. Should be possible to generate a direct link to current filter.

**Comment by fredriklindman** [comment]
Current design

![filter](https://f.cloud.github.com/assets/1004145/268066/7ab78f38-8f01-11e2-9075-66522469146f.png)

**Comment by nilsi** [comment]
Looks good, but im not sure about the button? I guess it's there for filtering stories that are selected but is that needed? We could also have filter on type in the filter input field?

**Comment by fredriklindman** [comment]
Currently you can do both, filtering is activated both on type in the input field and by selecting items and pressing the button. I added the button in order to take away the work of typing all IDs if a user wants to filter on many items and because I thought it was natural together with the print button.

The design is open for discussion of course. Gustaf and Jonas what do you think?

**Comment by GLundh** [comment]
I think we need the button. Since the ID does not have a high visibility, some people may not even draw the conclusion that they can use the "arbitrary little black numbers in the right bottom corner" for filtering the list :)

+1 for button.

**Comment by nilsi** [comment]
Aha I misunderstood the use of the button. But yes that can be useful. What do you think about the position of the ID? we could have it as a tag also maybe? like we have story, epic, theme tags now. The numbers id's could be to large numbers after a while though.
