### ISSUE TITLE
Oracle support

### ISSUE THREAD

**Issue by zerlite2112** [sonyxperiadev/BacklogTool#3]
Hi!,
We are evaluating the tool for use with our team, to replace our existing backtracking tool.
We would like to ask does it support Oracle for the Database? we intend to use our existing database infrastructure which is Oracle.

Thank you very much.

Gerald

**Comment by fredriklindman** [comment]
Hi! 

Great that this tool is on your list! As you may have seen, we use Hibernate for database management and therefore it's at least in theory very easy to support several DB types including Oracle. Also I can't find anything that should limit us from allowing Oracle DB by a few lines of code. We will have to further look into it but the preliminary answer to your question is Yes. 

Fredrik

**Comment by zerlite2112** [comment]
Hi Fredrik,
Good day.
I got it working with our oracle db, but the db that I'm using right now is a shared db for our team.
Can you please provide me the tables that backlogtool is using/created.

Thanks,
Gerald

**Comment by fredriklindman** [comment]
Hi Gerald! 

Great that you got it working! I don't currently have access to a database with Backlogtool, but hopefully Gustaf Lundh reads this and can give an accurate answer! 

Fredrik

**Comment by zerlite2112** [comment]
Hi Fredrik,
Good day.
One of may teammate got already the tables that was created yesterday.

Thanks for the help.

Gerald
