### ISSUE TITLE
Is pushing new information to Chrome broken?

### ISSUE THREAD

**Issue by fredriklindman** [sonyxperiadev/BacklogTool#39]
It seems like the newer versions of Chrome are unable to recieve push notifications when other users make changes to the same area. At least it's not working for me locally with Chrome version 26.0.1410. Can someone please confirm this? It still seems to be working in Firefox.

If confirmed, we should look into updating ICEPush..

**Comment by nilsi** [comment]
Yes I noticed this also.

**Comment by fredriklindman** [comment]
I tried to update ICEPush from version 3.0.1 to 3.2.0 but it did not make any difference. Gustaf or Jonas, do you have the same problem in production?

**Comment by fredriklindman** [comment]
The problem does not exist when running on a dedicated Tomcat server - closing.
