### ISSUE TITLE
Disable create button while editing

### ISSUE THREAD

**Issue by nilsi** [sonyxperiadev/BacklogTool#40]
If a user is editing a backlog item and decides to create a new one the UI will refresh and the changes is lost. This could be solved by disable the create button while the user have items in edit mode, or something.

**Comment by fredriklindman** [comment]
Note that the problem also applies for creating new child items.

**Comment by fredriklindman** [comment]
This is an ongoing change. We will not disable the create button, but make sure all data is kept after the new item has been created. In other words, items that are in "edit mode" will stay there until the user saves or cancels, even though he creates new items.

**Comment by fredriklindman** [comment]
Solved in version 1.2.0, closing.
