### ISSUE TITLE
Special characters in themes, epics

### ISSUE THREAD

**Issue by Galilleo** [sonyxperiadev/BacklogTool#5]
When creating a new epic in a theme with a special character in its name, a new theme is created with the same name containing the new epic. Same behavior is with the epic-story. Havent been testing the story-task.

To reproduce:
1. Create a theme named: 10°C
2. Click + button to add a new epic.

**Comment by GLundh** [comment]
Thanks for the report. I'll look into it!

Cheers
G

**Comment by fredriklindman** [comment]
It should now be fixed, you can download the new source code or war file.

/Fredrik

**Comment by GLundh** [comment]
Thanks, Fredrik!

**Comment by Galilleo** [comment]
No problem with names now :) Thanks!
