### ISSUE TITLE
Support automated task state transitions

### ISSUE THREAD

**Issue by dpursehouse** [sonyxperiadev/BacklogTool#9]
As a Gerrit user, I want to be able to upload changes to Gerrit with a specific footer tag in the commit message (for example "Closes: Task 1234"), and have a Gerrit plugin automate the state transition of the task when the change is submitted.

**Comment by fredriklindman** [comment]
I've thought about this some more and the only problem I see is the authentication of the request. We currently only allow users that are logged in via the website to make requests, which means that RESTful API authentication must implemented. Here's an article and example on the subject:
http://kevinpotgieter.wordpress.com/2012/05/14/spring-3-1-restful-authentication/

When that's finished, it would be very easy to send the task id and new status id as parameters with the request to make the change.

I will see if I can get time for this further on.
